### PR TITLE
Turn time string into time object

### LINKED ISSUE #12: Receiving "undefined method 'utc' error" when attempting to transition to the 'failing' tab
Error message in terminal:

2015-04-08 10:04:28 - NoMethodError - undefined method `utc' for "2015-04-08 17:08:06.843141":String:
	/...gems/que-web-0.3.2/lib/que/web.rb:112:in `relative_time'

### PR DESCRIPTION
**Pull request by sstgithub**
fixes #12

### CODE REVIEW

**Comment by statianzo** [comment]
Just curious for testing, what setup (ORM, Ruby, OS, PG version) are you using to get dates back as strings?

**Comment by sstgithub** [comment]
I'm using Ruby on Rails (Ruby 2.2.1 and Rails 4.1.0) with Postgres 9.3.5 on Mac OSX 10.9.5

**Comment by statianzo** [comment]
Merged for right now to solve your immediate case, but I'd prefer if I could get the SQL to return DateTime objects.

**Comment by sstgithub** [comment]
Thanks for merging. For me, Que saves run_at as a string. Is Que supposed to save run_at as a DateTime object or am I misunderstanding what you are saying?

**Comment by joevandyk** [comment]
`que_jobs.run_at` is supposed to be a timestamptz in the database. I think your setup isn't right?

```
tanga_dev=# \d que_jobs
                                      Table "public.que_jobs"
   Column    |           Type           |                         Modifiers
-------------+--------------------------+-----------------------------------------------------------
 priority    | smallint                 | not null default 100
 run_at      | timestamp with time zone | not null default now()
 job_id      | bigint                   | not null default nextval('que_jobs_job_id_seq'::regclass)
 job_class   | text                     | not null
 args        | json                     | not null default '[]'::json
 error_count | integer                  | not null default 0
 last_error  | text                     |
 queue       | text                     | not null default ''::text
```

**Comment by sstgithub** [comment]
@joevandyk you were right, I missed this part in the readme for Que gem!: 
> If you're using ActiveRecord to dump your database's schema, you'll probably want to set schema_format to :sql so that Que's table structure is managed correctly.

**Comment by joevandyk** [comment]
:) I would unmerge this then? 

I've seen that problem bite a lot of people.

**Comment by sstgithub** [comment]
Created a new pull request to unmerge #14

**Pull request merged**
